name: CI Semillero

on:
  push:
    branches: [ "semillero20232-1" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: "cacevedod/fastapi"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3.1.4
    - name: dependencias python
      run: "pip install --no-cache-dir --upgrade -r requirements.txt"
    - name: unit test python
      run: "python -m unittest discover tests"
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.9.1
    - name: SonarQube Quality Gate Check
      uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
  
  
  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
